runtime: nodejs14
service: default
env: standard

entrypoint: npm install --force

handlers:
  - url: /
    static_files: build/index.html
    upload: build/index.html
  - url: /(.*)$
    static_files: build/\1
    upload: build/(.*)

instance_class: F2