#server:
#  port: ${PORT:8080}
#  servlet:
#    context-path: /bikesharing


spring:
  config:
    additional-location: ${SPRING_CONFIG_ADDITIONAL_LOCATION}
  jpa:
    defer-datasource-initialization: true
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  sql:
    init:
      mode: always
  cloud:
    gcp:
      sql:
        database-name: ${DB_NAME:dbbikesharing}
        instance-connection-name: ${DB_INSTANCE:kdg-acs3-integration-5-team-2:europe-west1:dbintegration}
  datasource:
#    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3308/bike_test_db}
#    username: ${DATASOURCE_USER:user}
#    password: ${DATASOURCE_PASS:password}

    username: ${DATASOURCE_USER:root}
    password: ${DATASOURCE_PASS:admin}


  rabbitmq:
    host: localhost
    port: 5672
    username: myuser
    password: mypassword
    